import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1400, height: 900 } })
await p.goto('http://localhost:5273/')
await p.evaluate(() => localStorage.clear())
await p.reload()
await p.getByRole('combobox').selectOption({ label: 'Biology B.A. ✓' })
await p.getByRole('button', { name: /Biology B\.A\./ }).first().click()
await p.getByText(/Recommended prior to transfer to ensure timely graduation/).first().waitFor()
console.log('biology-ba dropped note now renders: OK')
await b.close()
