"""modality free text

Revision ID: 1a988bb2cf53
Revises: f6800d0d7e17
Create Date: 2026-07-25 14:59:04.240871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a988bb2cf53'
down_revision: Union[str, None] = 'f6800d0d7e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_offerings', 'modality',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_offerings', 'modality',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
