"""status free text

Revision ID: 4edb8c353a97
Revises: 1a988bb2cf53
Create Date: 2026-07-25 16:53:31.824905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4edb8c353a97'
down_revision: Union[str, None] = '1a988bb2cf53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_offerings', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_offerings', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
