"""course dormant flag

Revision ID: 66a5b8cd01a9
Revises: 4edb8c353a97
Create Date: 2026-07-27 15:07:57.860666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66a5b8cd01a9'
down_revision: Union[str, None] = '4edb8c353a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('dormant', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'dormant')
    # ### end Alembic commands ###
