"""initial schema

Revision ID: f6800d0d7e17
Revises: 
Create Date: 2026-07-25 13:53:27.183236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f6800d0d7e17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('term_system', sa.String(length=16), nullable=False),
    sa.Column('catalog_year', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_token_hash'), 'auth_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=8), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('display_code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('credits', sa.String(length=16), nullable=False),
    sa.Column('division', sa.String(length=16), nullable=False),
    sa.Column('ge_codes', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('quarters_offered_text', sa.Text(), nullable=True),
    sa.Column('catalog_instructor', sa.Text(), nullable=True),
    sa.Column('cross_listed', postgresql.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('formerly', sa.Text(), nullable=True),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_requirements', sa.Text(), nullable=True),
    sa.Column('prereq_groups', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'code')
    )
    op.create_index('ix_courses_univ_subject', 'courses', ['university_id', 'subject'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('program_ids', postgresql.ARRAY(sa.Integer()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('degree', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('catalog_year', sa.String(length=16), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('verification', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'slug')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('sort_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'code')
    )
    op.create_index(op.f('ix_terms_sort_key'), 'terms', ['sort_key'], unique=False)
    op.create_table('course_availability',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('season_counts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('last_offered_term_code', sa.String(length=8), nullable=True),
    sa.Column('next_planned', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('predicted_instructors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.String(length=32), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=16), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=8), nullable=True),
    sa.Column('class_number', sa.String(length=16), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('instructors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('days_times', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(length=32), nullable=True),
    sa.Column('enrolled', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offerings_term', 'course_offerings', ['term_id'], unique=False)
    op.create_index('ix_offerings_univ_code', 'course_offerings', ['university_id', 'course_code'], unique=False)
    op.create_table('course_prereq_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prereq_code', sa.String(length=16), nullable=False),
    sa.Column('prereq_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prereq_course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prereq_code')
    )
    op.create_index('ix_prereq_edges_prereq_code', 'course_prereq_edges', ['prereq_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prereq_edges_prereq_code', table_name='course_prereq_edges')
    op.drop_table('course_prereq_edges')
    op.drop_index('ix_offerings_univ_code', table_name='course_offerings')
    op.drop_index('ix_offerings_term', table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_table('course_availability')
    op.drop_index(op.f('ix_terms_sort_key'), table_name='terms')
    op.drop_table('terms')
    op.drop_table('programs')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_courses_univ_subject', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_hash'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('universities')
    # ### end Alembic commands ###
